version: '3.4'
services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
  dynamodb-admin:
    build: ./docker/dynamodb-admin
    command: dynamodb-admin -p 8001
    environment:
      DYNAMO_ENDPOINT: http://localstack:4566
      AWS_REGION: local
      AWS_ACCESS_KEY_ID: localstack
      AWS_SECRET_ACCESS_KEY: localstack
    ports:
      - '8001:8001'
    depends_on:
      - localstack
